import './main.scss';

export const metadata = {
  title: 'it finland docs',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <div className="card">{children}</div>
      </body>
    </html>
  );
}
